spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: language_courses
      username: root
      password: example

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_migration
    username: postgres
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect